apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wjr1xu3r4-nodejs
  janus-idp.io/tekton: wjr1xu3r4-nodejs
  backstage.io/kubernetes-id: wjr1xu3r4-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wjr1xu3r4-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
